### PR TITLE
moved npm-asset dependencies to separate file

### PR DESCRIPTION
**Pull request by schmunk42**
Allow installation of package with native JS tooling (npm, yarn)

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | ?
| Fixed issues  | #5

### CODE REVIEW

**Comment by SamMousa** [comment]
Who is responsible for parsing this file? I imagine npm / yarn don't support it natively?

**Comment by schmunk42** [comment]
The https://github.com/wikimedia/composer-merge-plugin merges the `composer.assets.json` files if it is configured to do so. The resulting merge is equivalent to the current `composer.json` file.

The problem is, when there's a `npm-asset` in `composer.json` you CAN NOT use it **without** asset-packagist, because you are not able to get rid of it, since it is in a dependency.

**Comment by SamMousa** [comment]
From the docs  here: `https://github.com/yiisoft/yii-project-template/blob/master/README.md`

Could we move this part into the `composer.asset.json` as well?
```
composer config repositories.ap '{"type": "composer", "url": "https://asset-packagist.org"}'
```

I realise how the composer part works. But how would I use NPM with that file?

**Comment by schmunk42** [comment]
You can't use `npm` with that file, you'd just install Foxy and it takes care about passing the `packages.json` file from the extensions to `npm`.

**Comment by samdark** [comment]
OK. Let's have it like that. At least for now...

**Pull request merged**
